Repository mesosphere/dcos-docs-site, pull requests merged in 2018-07, with the labels that each got.

#1159 Increase the agent requirements for `/var` free space to 20 GB
  pages/1.10/installing/ent/custom/system-requirements/index.md
  pages/1.10/installing/oss/custom/system-requirements/index.md
  pages/1.11/installing/ent/custom/system-requirements/index.md
  pages/1.11/installing/oss/custom/system-requirements/index.md
Labels: needs review

#1173 Fixed checkpointed resources removal omission.
  pages/1.11/storage/mount-disk-resources/index.md
Labels: ready to merge

#1225 Add documentation for Elastic 2.4.0-5.6.9.
  pages/services/elastic/2.4.0-5.6.9/advanced/index.md
  pages/services/elastic/2.4.0-5.6.9/api-reference/index.md
  pages/services/elastic/2.4.0-5.6.9/configuration/index.md
  pages/services/elastic/2.4.0-5.6.9/getting-started/index.md
  pages/services/elastic/2.4.0-5.6.9/img/private-node-by-vip.png
  pages/services/elastic/2.4.0-5.6.9/img/private-nodes-by-agent.png
  pages/services/elastic/2.4.0-5.6.9/img/x-pack.png
  pages/services/elastic/2.4.0-5.6.9/index.md
  pages/services/elastic/2.4.0-5.6.9/limitations/index.md
  pages/services/elastic/2.4.0-5.6.9/operations/index.md
  pages/services/elastic/2.4.0-5.6.9/release-notes/index.md
  pages/services/elastic/2.4.0-5.6.9/security/index.md
  pages/services/elastic/2.4.0-5.6.9/support-policy/index.md
  pages/services/elastic/2.4.0-5.6.9/troubleshooting/index.md
  pages/services/elastic/2.4.0-5.6.9/uninstall/index.md
  pages/services/elastic/2.4.0-5.6.9/updates/index.md
Labels: needs review, p1 - high

#1224 Add Cassandra 2.3.0-3.0.16 documentation.
  pages/services/cassandra/2.3.0-3.0.16/advanced/index.md
  pages/services/cassandra/2.3.0-3.0.16/api-reference/index.md
  pages/services/cassandra/2.3.0-3.0.16/configuration/index.md
  pages/services/cassandra/2.3.0-3.0.16/getting-started/index.md
  pages/services/cassandra/2.3.0-3.0.16/index.md
  pages/services/cassandra/2.3.0-3.0.16/limitations/index.md
  pages/services/cassandra/2.3.0-3.0.16/operations/index.md
  pages/services/cassandra/2.3.0-3.0.16/release-notes/index.md
  pages/services/cassandra/2.3.0-3.0.16/security/index.md
  pages/services/cassandra/2.3.0-3.0.16/support-policy/index.md
  pages/services/cassandra/2.3.0-3.0.16/troubleshooting/index.md
  pages/services/cassandra/2.3.0-3.0.16/uninstall/index.md
  pages/services/cassandra/2.3.0-3.0.16/updates/index.md
Labels: needs review, p1 - high

#1136 Prometheus service guide PR
  pages/services/prometheus/0.1.0-2.3.2/Operations/index.md
  pages/services/prometheus/0.1.0-2.3.2/configuration/alerting-overview/index.md
  pages/services/prometheus/0.1.0-2.3.2/configuration/index.md
  pages/services/prometheus/0.1.0-2.3.2/configuration/prometheus-federation/index.md
  pages/services/prometheus/0.1.0-2.3.2/configuration/remote-storage/index.md
  pages/services/prometheus/0.1.0-2.3.2/configuration/service-discovery/index.md
  pages/services/prometheus/0.1.0-2.3.2/configuration/visualization/index.md
  pages/services/prometheus/0.1.0-2.3.2/getting-started/index.md
  pages/services/prometheus/0.1.0-2.3.2/img/am_dashboard.png
  pages/services/prometheus/0.1.0-2.3.2/img/grafana_datasource.png
  pages/services/prometheus/0.1.0-2.3.2/img/grafana_login.png
  pages/services/prometheus/0.1.0-2.3.2/img/grafana_prom.png
  pages/services/prometheus/0.1.0-2.3.2/img/prom_dashboard.png
  pages/services/prometheus/0.1.0-2.3.2/img/prom_graphing.png
  pages/services/prometheus/0.1.0-2.3.2/img/prom_install.png
  pages/services/prometheus/0.1.0-2.3.2/img/pushg.png
  pages/services/prometheus/0.1.0-2.3.2/img/slack_alert.png
  pages/services/prometheus/0.1.0-2.3.2/index.md
  pages/services/prometheus/0.1.0-2.3.2/limitations/index.md
  pages/services/prometheus/0.1.0-2.3.2/quick-start-guide/index.md
  pages/services/prometheus/0.1.0-2.3.2/release-notes/index.md
  pages/services/prometheus/0.1.0-2.3.2/security/index.md
  pages/services/prometheus/0.1.0-2.3.2/supported-versions/index.md
  pages/services/prometheus/0.1.0-2.3.2/troubleshooting/index.md
  pages/services/prometheus/0.1.0-2.3.2/uninstall/index.md
  pages/services/prometheus/data.yml
  pages/services/prometheus/index.md
Labels: p1 - high
