Repository mesosphere/dcos-docs-site, pull requests merged in 2018-12, with the labels that each got.

#1728 ck/COPS-4045 Update cpu scheduling page
  pages/1.12/monitoring/debugging/slow-docker/index.md
Labels: needs review

#1804 LG/COPS-4202 Remove Network metrics from 1.10 and 1.11 per Support re…
  pages/1.10/metrics/reference/index.md
  pages/1.11/metrics/reference/index.md
Labels: needs review

#1817 COPS-4275 Fix fault_domain output format
  pages/1.10/installing/production/deploying-dcos/installation/index.md
  pages/1.11/deploying-services/fault-domain-awareness/index.md
  pages/1.11/hybrid-cloud/capacity-extension-with-regions/index.md
  pages/1.11/installing/production/deploying-dcos/installation/index.md
  pages/1.12/deploying-services/fault-domain-awareness/index.md
  pages/1.12/hybrid-cloud/capacity-extension-with-regions/index.md
  pages/1.12/installing/production/deploying-dcos/installation/index.md
  pages/cn/1.11/deploying-services/fault-domain-awareness/index.md
  pages/cn/1.11/hybrid-cloud/features/capacity-extension-with-regions/index.md
Labels: needs review, p0 - critical

#1806 ss/DCOS-33518 Adding HTTPS_PROXY setting to Backup instructions.
  pages/services/cassandra/2.4.0-3.0.16/operations/index.md
Labels: needs review, p1 - high
