Repository mesosphere/dcos-docs-site, pull requests merged in 2018-08, with the labels that each got.

#1266 Update superuser permissions description to be more precise
  pages/1.10/security/ent/perms-reference/index.md
  pages/1.11/security/ent/perms-reference/index.md
  pages/1.12/security/ent/perms-reference/index.md
Labels: needs review

#1258 Some services/kubernetes doc changes
  pages/services/kubernetes/1.0.0-1.9.3/advanced-install/index.md
  pages/services/kubernetes/1.0.0-1.9.3/disaster-recovery/index.md
  pages/services/kubernetes/1.0.0-1.9.3/ingress/index.md
  pages/services/kubernetes/1.0.1-1.9.4/advanced-install/index.md
  pages/services/kubernetes/1.0.1-1.9.4/disaster-recovery/index.md
  pages/services/kubernetes/1.0.1-1.9.4/ingress/index.md
  pages/services/kubernetes/1.0.2-1.9.6/advanced-install/index.md
  pages/services/kubernetes/1.0.2-1.9.6/disaster-recovery/index.md
  pages/services/kubernetes/1.0.2-1.9.6/ingress/index.md
  pages/services/kubernetes/1.0.3-1.9.7/advanced-install/index.md
  pages/services/kubernetes/1.0.3-1.9.7/disaster-recovery/index.md
  pages/services/kubernetes/1.0.3-1.9.7/ingress/index.md
  pages/services/kubernetes/1.1.0-1.10.3/advanced-install/index.md
  pages/services/kubernetes/1.1.0-1.10.3/disaster-recovery/index.md
  pages/services/kubernetes/1.1.0-1.10.3/ingress/index.md
  pages/services/kubernetes/1.1.0-1.10.3/kubernetes-dashboard/index.md
  pages/services/kubernetes/1.1.1-1.10.4/advanced-install/index.md
  pages/services/kubernetes/1.1.1-1.10.4/disaster-recovery/index.md
  pages/services/kubernetes/1.1.1-1.10.4/ingress/index.md
  pages/services/kubernetes/1.1.1-1.10.4/kubernetes-dashboard/index.md
  pages/services/kubernetes/1.2.0-1.10.5/advanced-install/index.md
  pages/services/kubernetes/1.2.0-1.10.5/disaster-recovery/index.md
  pages/services/kubernetes/1.2.0-1.10.5/ingress/index.md
  pages/services/kubernetes/1.2.0-1.10.5/kubernetes-dashboard/index.md
Labels: needs review

#1307 Add information about the new install-time param: `mesosAuthNZ`
  pages/services/edge-lb/1.0/installing/index.md
  pages/services/edge-lb/1.0/upgrading/index.md
Labels: needs review, p0 - critical, ready to merge

#1239 EdgeLB v1.1.0 release notes
  pages/1.11/networking/load-balancing-vips/index.md
  pages/services/edge-lb/1.0/release-notes/index.md
Labels: needs review, p0 - critical, ready to merge

#1342 Document new ``permissions_cache_ttl_seconds`` configuration parameter.
  pages/1.12/installing/production/advanced-configuration/configuration-reference/index.md
Labels: needs review

#1256 [DCOS-38720] Add docs for HDFS 2.3.0-2.6.0-cdh5.11.0
  pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/advanced/index.md
  pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/api-reference/index.md
  pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/configuration/index.md
  pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/getting-started/index.md
  pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/index.md
  pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/limitations/index.md
  pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/operations/index.md
  pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/release-notes/index.md
  pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/security/index.md
  pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/support-policy/index.md
  pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/troubleshooting/index.md
  pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/uninstall/index.md
  pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/updates/index.md
Labels: needs review

#1346 Remove stale documentation from local universe deployment
  pages/1.10/administering-clusters/deploying-a-local-dcos-universe/index.md
  pages/1.11/administering-clusters/deploying-a-local-dcos-universe/index.md
  pages/1.12/administering-clusters/deploying-a-local-dcos-universe/index.md
  pages/1.7/administration/installing/ent/custom/deploying-a-local-dcos-universe/index.md
  pages/1.9/administering-clusters/deploying-a-local-dcos-universe/index.md
Labels: p3 - low
