Repository mesosphere/dcos-docs-site, pull requests merged in 2018-10, with the labels that each got.

#1511 kubernetes: quickstart and other release script changes
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/authn-and-authz/index.md
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/exposing-the-kubernetes-api-marathonlb/index.md
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/exposing-the-kubernetes-api/index.md
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/install/index.md
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/quick-start/index.md
  scripts/service-update-scripts/kubernetes-merge-branch.sh
  scripts/service-update-scripts/kubernetes-merge.sh
Labels: p0 - critical, ready to merge

#1481 Add Python to Docker container
  docker/Dockerfile.docs
Labels: needs review

#1546 Remove dupe html block in 1.12 architecture/components docs
  pages/1.12/overview/architecture/components/index.md
Labels: p2 - normal

#1524 Missing rename for percona-mongo -> percona-server-mongodb
  pages/services/percona-server-mongodb/index.md
Labels: ready to merge

#1555 1.12 Multi-tenancy Primitives documentation
  pages/1.12/deploying-services/multi-tenancy-primitives/index.md
Labels: needs review

#1598 1.12,1.11,1.10 - System Requirements docs: Added customer advisory in…
  pages/1.10/installing/ent/custom/system-requirements/install-docker-centos/index.md
  pages/1.11/installing/production/system-requirements/docker-centos/index.md
  pages/1.12/installing/production/system-requirements/docker-centos/index.md
Labels: needs review

#1592 Added new entries, arranged entries in alphabetical order, and fixed …
  pages/version-policy/index.md
Labels: needs review
