Repository mesosphere/dcos-docs-site, pull requests merged in 2018-11, with the labels that each got.

#1629 [DCOS-43384] release cassandra 2.4.0-3.0.16
  pages/services/cassandra/2.4.0-3.0.16/advanced/index.md
  pages/services/cassandra/2.4.0-3.0.16/api-reference/index.md
  pages/services/cassandra/2.4.0-3.0.16/configuration/index.md
  pages/services/cassandra/2.4.0-3.0.16/getting-started/index.md
  pages/services/cassandra/2.4.0-3.0.16/index.md
  pages/services/cassandra/2.4.0-3.0.16/limitations/index.md
  pages/services/cassandra/2.4.0-3.0.16/operations/index.md
  pages/services/cassandra/2.4.0-3.0.16/release-notes/index.md
  pages/services/cassandra/2.4.0-3.0.16/security/index.md
  pages/services/cassandra/2.4.0-3.0.16/support-policy/index.md
  pages/services/cassandra/2.4.0-3.0.16/troubleshooting/index.md
  pages/services/cassandra/2.4.0-3.0.16/uninstall/index.md
  pages/services/cassandra/2.4.0-3.0.16/updates/index.md
Labels: needs review

#1616 [DCOS-43590] Release dse 2.4.0-5.1.10
  pages/services/dse/2.4.0-5.1.10/advanced/index.md
  pages/services/dse/2.4.0-5.1.10/api-reference/index.md
  pages/services/dse/2.4.0-5.1.10/configuration/index.md
  pages/services/dse/2.4.0-5.1.10/getting-started/index.md
  pages/services/dse/2.4.0-5.1.10/index.md
  pages/services/dse/2.4.0-5.1.10/limitations/index.md
  pages/services/dse/2.4.0-5.1.10/operations/index.md
  pages/services/dse/2.4.0-5.1.10/release-notes/index.md
  pages/services/dse/2.4.0-5.1.10/security/index.md
  pages/services/dse/2.4.0-5.1.10/support-policy/index.md
  pages/services/dse/2.4.0-5.1.10/troubleshooting/index.md
  pages/services/dse/2.4.0-5.1.10/uninstall/index.md
  pages/services/dse/2.4.0-5.1.10/updates/index.md
Labels: needs review

#1690 Release notes for Edge-LB v1.2.2
  pages/services/edge-lb/1.2/release-notes/index.md
Labels: needs review, p1 - high

#1746 Update update.tmpl
  pages/services/include/update.tmpl
Labels: needs review, ready to merge

#1710 ss/DCOS-44616 Adding Advanced Azure page to install docs.
  pages/1.12/installing/evaluation/mesosphere-supported-methods/azure/advanced-azure/index.md
Labels: needs review

#1757 ck/COPS-4020 Add task attach page
  pages/1.12/cli/command-reference/dcos-task/dcos-task-attach/index.md
Labels: needs review
