Repository mesosphere/dcos-docs-site, pull requests merged in 2018-09, with the labels that each got.

#1411 Percona-mongo: update JSON user examples to have quoted keys
  pages/services/percona-mongo/0.3.0-3.6.5/quick-start/index.md
  pages/services/percona-mongo/0.3.1-3.6.5/quick-start/index.md
Labels: ready to merge

#1381 Document recently added resource provider-related permissions
  pages/1.12/security/ent/perms-reference/index.md
Labels: needs review

#1308 Kubernetes service docs layout
  pages/services/kubernetes/1.0.0-1.9.3/advanced-install/index.md
  pages/services/kubernetes/1.0.1-1.9.4/advanced-install/index.md
  pages/services/kubernetes/1.0.2-1.9.6/advanced-install/index.md
  pages/services/kubernetes/1.0.2-1.9.6/release-notes/index.md
  pages/services/kubernetes/1.0.3-1.9.7/advanced-install/index.md
  pages/services/kubernetes/1.1.0-1.10.3/advanced-install/index.md
  pages/services/kubernetes/1.1.1-1.10.4/advanced-install/index.md
  pages/services/kubernetes/1.1.1-1.10.4/exposing-the-kubernetes-api/index.md
  pages/services/kubernetes/1.2.0-1.10.5/advanced-install/index.md
  pages/services/kubernetes/1.2.0-1.10.5/exposing-the-kubernetes-api/index.md
  pages/services/kubernetes/1.2.0-1.10.5/install/index.md
  pages/services/kubernetes/1.2.1-1.10.6/advanced-install/index.md
  pages/services/kubernetes/1.2.1-1.10.6/exposing-the-kubernetes-api/index.md
  pages/services/kubernetes/1.2.1-1.10.6/install/index.md
  scripts/service-update-scripts/kubernetes-merge-branch.sh
  scripts/service-update-scripts/kubernetes-merge.sh
Labels: p1 - high, ready to merge

#1435 Release notes and documentation for Edge-LB v1.2
  pages/services/edge-lb/1.2/api-reference/haproxy/index.md
  pages/services/edge-lb/1.2/api-reference/index.md
  pages/services/edge-lb/1.2/api-reference/v1/index.md
  pages/services/edge-lb/1.2/api-reference/v2/index.md
  pages/services/edge-lb/1.2/cli-reference/dcos-edgelb-create/index.md
  pages/services/edge-lb/1.2/cli-reference/dcos-edgelb-delete/index.md
  pages/services/edge-lb/1.2/cli-reference/dcos-edgelb-endpoints/index.md
  pages/services/edge-lb/1.2/cli-reference/dcos-edgelb-lb-config/index.md
  pages/services/edge-lb/1.2/cli-reference/dcos-edgelb-list/index.md
  pages/services/edge-lb/1.2/cli-reference/dcos-edgelb-ping/index.md
  pages/services/edge-lb/1.2/cli-reference/dcos-edgelb-show/index.md
  pages/services/edge-lb/1.2/cli-reference/dcos-edgelb-status/index.md
  pages/services/edge-lb/1.2/cli-reference/dcos-edgelb-template-create/index.md
  pages/services/edge-lb/1.2/cli-reference/dcos-edgelb-template-delete/index.md
  pages/services/edge-lb/1.2/cli-reference/dcos-edgelb-template-show/index.md
  pages/services/edge-lb/1.2/cli-reference/dcos-edgelb-template-update/index.md
  pages/services/edge-lb/1.2/cli-reference/dcos-edgelb-update/index.md
  pages/services/edge-lb/1.2/cli-reference/dcos-edgelb-version/index.md
  pages/services/edge-lb/1.2/cli-reference/index.md
  pages/services/edge-lb/1.2/img/edge-lb-flow.png
  pages/services/edge-lb/1.2/index.md
  pages/services/edge-lb/1.2/input-formats/index.md
  pages/services/edge-lb/1.2/installing/index.md
  pages/services/edge-lb/1.2/permissions/index.md
  pages/services/edge-lb/1.2/pool-configuration/index.md
  pages/services/edge-lb/1.2/pool-configuration/v1-examples/index.md
  pages/services/edge-lb/1.2/pool-configuration/v1-reference/index.md
  pages/services/edge-lb/1.2/pool-configuration/v2-examples/index.md
  pages/services/edge-lb/1.2/pool-configuration/v2-reference/index.md
  pages/services/edge-lb/1.2/release-notes/index.md
  pages/services/edge-lb/1.2/tutorials/blue-green-deploy/index.md
  pages/services/edge-lb/1.2/tutorials/index.md
  pages/services/edge-lb/1.2/tutorials/multi-lb/index.md
  pages/services/edge-lb/1.2/tutorials/single-lb/index.md
  pages/services/edge-lb/1.2/uninstalling/index.md
  pages/services/edge-lb/1.2/upgrading/index.md
  pages/services/edge-lb/1.2/usage/index.md
Labels: p1 - high

#1446 Add to Limitations docs for https://github.com/dcos_mongo/issues/265
  pages/services/percona-server-mongodb/0.4.0-3.6.6/limitations/index.md
Labels: ready to merge

#1451 Removed DataDog page from 1.12/metrics/.
  pages/1.12/metrics/datadog/index.md
Labels: needs review

#1359 [WIP] DCOS-40141: Add SELinux support
  pages/1.12/installing/production/system-requirements/index.md
Labels: needs review

#1360 [WIP] DCOS-40141: Add SELinux support (without CoreOS)
  pages/1.12/installing/production/system-requirements/index.md
Labels: needs review

#1424 Couchbase Service Guide 0.2.0-5.5.0
  pages/services/couchbase/0.2.0-5.5.0/configuration/index.md
  pages/services/couchbase/0.2.0-5.5.0/getting-started/index.md
  pages/services/couchbase/0.2.0-5.5.0/img/add_user.png
  pages/services/couchbase/0.2.0-5.5.0/img/couch_3.png
  pages/services/couchbase/0.2.0-5.5.0/img/couch_creds.png
  pages/services/couchbase/0.2.0-5.5.0/img/couch_dashboard.png
  pages/services/couchbase/0.2.0-5.5.0/img/couch_dev_conf_1.png
  pages/services/couchbase/0.2.0-5.5.0/img/couch_dev_conf_2.png
  pages/services/couchbase/0.2.0-5.5.0/img/couch_dev_conf_3.png
  pages/services/couchbase/0.2.0-5.5.0/img/couch_dnodes.png
  pages/services/couchbase/0.2.0-5.5.0/img/couch_edit.png
  pages/services/couchbase/0.2.0-5.5.0/img/couch_install.png
  pages/services/couchbase/0.2.0-5.5.0/img/couch_install_finished.png
  pages/services/couchbase/0.2.0-5.5.0/img/couch_prod_conf_1.png
  pages/services/couchbase/0.2.0-5.5.0/img/couch_prod_conf_2.png
  pages/services/couchbase/0.2.0-5.5.0/img/data_bucket.png
  pages/services/couchbase/0.2.0-5.5.0/img/edit_conf.png
  pages/services/couchbase/0.2.0-5.5.0/img/running.png
  pages/services/couchbase/0.2.0-5.5.0/img/todos.png
  pages/services/couchbase/0.2.0-5.5.0/index.md
  pages/services/couchbase/0.2.0-5.5.0/limitations/index.md
  pages/services/couchbase/0.2.0-5.5.0/operations/index.md
  pages/services/couchbase/0.2.0-5.5.0/quick-start-guide/index.md
  pages/services/couchbase/0.2.0-5.5.0/release-notes/index.md
  pages/services/couchbase/0.2.0-5.5.0/security/index.md
  pages/services/couchbase/0.2.0-5.5.0/supported-versions/index.md
  pages/services/couchbase/0.2.0-5.5.0/troubleshooting/index.md
  pages/services/couchbase/0.2.0-5.5.0/uninstall/index.md
  pages/services/couchbase/data.yml
  pages/services/couchbase/index.md
  pages/services/include/configuration-install-with-options.tmpl
  pages/services/include/getting-started.tmpl
Labels: needs review

#1462 beta-kubernetes: package documentation for 2.0.0-1.12.0-beta
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/authn-and-authz/index.md
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/cluster_sizing/index.md
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/connecting-clients/index.md
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/disaster-recovery/index.md
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/exposing-the-kubernetes-api-marathonlb/index.md
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/exposing-the-kubernetes-api/index.md
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/img/authorization-mode.png
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/img/haproxy.png
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/img/marathonlb.png
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/img/services.png
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/img/tls.png
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/index.md
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/install/index.md
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/kubernetes-dashboard/index.md
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/limitations/index.md
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/quick-start/index.md
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/release-notes/index.md
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/supported-versions/index.md
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/troubleshooting-etcd/index.md
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/uninstall/index.md
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/upgrade/index.md
  pages/services/beta-kubernetes/index.md
Labels: p0 - critical, ready to merge

#1466 docs: remove misleading note about upgrades
  pages/services/beta-kubernetes/2.0.0-1.12.0-beta/release-notes/index.md
Labels: needs review, p0 - critical

#1472 removed another mentione re xdcr
  pages/services/couchbase/0.2.0-5.5.0/index.md
Labels: ready to merge

#1480 kubernetes: remove extra version string in the title
  pages/services/kubernetes/1.3.0-1.10.8/index.md
Labels: p1 - high, ready to merge

#1434 [DCOS-40953] release kafka zookeeper 2.4.0 3.4.13
  pages/services/kafka-zookeeper/2.4.0-3.4.13/advanced/index.md
  pages/services/kafka-zookeeper/2.4.0-3.4.13/api-reference/index.md
  pages/services/kafka-zookeeper/2.4.0-3.4.13/configuration/index.md
  pages/services/kafka-zookeeper/2.4.0-3.4.13/getting-started/index.md
  pages/services/kafka-zookeeper/2.4.0-3.4.13/index.md
  pages/services/kafka-zookeeper/2.4.0-3.4.13/limitations/index.md
  pages/services/kafka-zookeeper/2.4.0-3.4.13/operations/index.md
  pages/services/kafka-zookeeper/2.4.0-3.4.13/release-notes/index.md
  pages/services/kafka-zookeeper/2.4.0-3.4.13/security/index.md
  pages/services/kafka-zookeeper/2.4.0-3.4.13/support-policy/index.md
  pages/services/kafka-zookeeper/2.4.0-3.4.13/troubleshooting/index.md
  pages/services/kafka-zookeeper/2.4.0-3.4.13/uninstall/index.md
  pages/services/kafka-zookeeper/2.4.0-3.4.13/updates/index.md
Labels: needs review

#1438 [DCOS-40954] release confluent zookeeper 2.4.0 4.0.0e
  pages/services/confluent-zookeeper/2.4.0-4.0.0e/advanced/index.md
  pages/services/confluent-zookeeper/2.4.0-4.0.0e/api-reference/index.md
  pages/services/confluent-zookeeper/2.4.0-4.0.0e/configuration/index.md
  pages/services/confluent-zookeeper/2.4.0-4.0.0e/getting-started/index.md
  pages/services/confluent-zookeeper/2.4.0-4.0.0e/index.md
  pages/services/confluent-zookeeper/2.4.0-4.0.0e/limitations/index.md
  pages/services/confluent-zookeeper/2.4.0-4.0.0e/operations/index.md
  pages/services/confluent-zookeeper/2.4.0-4.0.0e/release-notes/index.md
  pages/services/confluent-zookeeper/2.4.0-4.0.0e/security/index.md
  pages/services/confluent-zookeeper/2.4.0-4.0.0e/support-policy/index.md
  pages/services/confluent-zookeeper/2.4.0-4.0.0e/troubleshooting/index.md
  pages/services/confluent-zookeeper/2.4.0-4.0.0e/uninstall/index.md
  pages/services/confluent-zookeeper/2.4.0-4.0.0e/updates/index.md
Labels: needs review

#1533 Add network security section
  pages/1.10/administering-clusters/securing-your-cluster/index.md
  pages/1.10/installing/ent/ports/index.md
  pages/1.10/installing/oss/ports/index.md
  pages/1.10/installing/ports/index.md
  pages/1.10/security/ent/hardening/index.md
  pages/1.10/security/oss/index.md
  pages/1.11/administering-clusters/securing-your-cluster/index.md
  pages/1.11/installing/production/system-requirements/ports/index.md
  pages/1.11/security/ent/hardening/index.md
  pages/1.11/security/oss/index.md
  pages/1.12/administering-clusters/securing-your-cluster/index.md
  pages/1.12/installing/production/system-requirements/ports/index.md
  pages/1.12/security/ent/hardening/index.md
  pages/1.12/security/oss/index.md
Labels: needs review

#1510 DCOS-42298: add priviledges note about dcos_marathon and dcos_metronome service accounts
  pages/1.11/security/ent/service-auth/custom-service-auth/index.md
  pages/1.12/security/ent/service-auth/custom-service-auth/index.md
Labels: needs review

#1403 1.12: Deploying Services using a Custom Marathon with Security Features
  pages/1.12/deploying-services/marathon-on-marathon/advanced/index.md
  pages/1.12/deploying-services/private-docker-registry/index.md
Labels: needs review, ready to merge

#1539 Backport Marathon-on-Marathon EE install instructions to 1.11
  pages/1.11/deploying-services/marathon-on-marathon/advanced/index.md
  pages/1.11/deploying-services/private-docker-registry/index.md
  pages/1.12/deploying-services/marathon-on-marathon/advanced/index.md
Labels: needs review, ready to merge
