Repository mesosphere/dcos-docs-site, pull requests merged in 2019-11, with the labels that each got.

#2607 ss/DCOS-60581 Fixing broken image link.
  pages/mesosphere/dcos/1.13/gui/services/index.md
Labels: ready to merge

#2616 DCOS-60471: Fix broken links for 3.6.0-2.190.1
  docker/nginx/redirects-307.map
  pages/mesosphere/dcos/services/jenkins/3.6.0-2.190.1/architecture/index.md
  pages/mesosphere/dcos/services/jenkins/3.6.0-2.190.1/quickstart/index.md
  pages/mesosphere/dcos/services/jenkins/3.6.0-2.190.1/release-notes/index.md
  pages/mesosphere/dcos/services/jenkins/3.6.0-2.190.1/upgrade/index.md
Labels: ready to merge

#2603 Fix typo : enforeceRole to enforceRole
  pages/mesosphere/dcos/2.0/multi-tenancy/quota-management/index.md
Labels: needs_jira, ready to merge

#2595 remove invalid symbols
  pages/mesosphere/dcos/1.11/networking/SDN/dcos-overlay/index.md
  pages/mesosphere/dcos/1.12/networking/SDN/dcos-overlay/index.md
  pages/mesosphere/dcos/1.13/networking/SDN/dcos-overlay/index.md
  pages/mesosphere/dcos/2.0/networking/SDN/dcos-overlay/index.md
Labels: needs_jira, ready to merge

#2615 Add a note about changes in Marathon instanceId handling which were i…
  pages/mesosphere/dcos/1.13/release-notes/1.13.0/index.md
Labels: needs_jira

#2620 creating draft release notes for 1.13.6
  pages/mesosphere/dcos/1.13/release-notes/1.13.6/index.md
Labels: ready to merge

#2628 ss/DCOS-60773 Regressed elk page to 1.13 version to reflect change fr…
  pages/mesosphere/dcos/2.0/monitoring/logging/aggregating/elk/index.md
Labels: ready to merge

#2626 Update index.md with D2iQ email address
  pages/mesosphere/dcos/2.0/release-notes/2.0.0/index.md
Labels: ready to merge, wip

#2629 updated Edge-LB docs so the bash copy script has correct download api…
  pages/mesosphere/dcos/services/edge-lb/1.4/getting-started/installing/index.md
  pages/mesosphere/dcos/services/edge-lb/1.5/getting-started/installing/index.md
  pages/mesosphere/dcos/services/edge-lb/1.5/img/edge-lb-catalog-titles-1.5.png
Labels: ready to merge

#2640 Fixing incorrect script example - COPS-4330
  pages/mesosphere/dcos/1.12/installing/production/deploying-dcos/installation/index.md
  pages/mesosphere/dcos/1.13/installing/production/deploying-dcos/installation/index.md
  pages/mesosphere/dcos/2.0/installing/production/deploying-dcos/installation/index.md
  pages/mesosphere/dcos/2.1/installing/production/deploying-dcos/installation/index.md
  pages/mesosphere/dcos/cn/1.12/installing/production/deploying-dcos/installation/index.md
Labels: ready to merge

#2641 dcos-monitoring: Update docs for 1.2.0
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/cli-references/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/cli-references/monitoring-prometheus/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/cli-references/monitoring-prometheus/monitoring-prometheus-alertmanagers/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/cli-references/monitoring-prometheus/monitoring-prometheus-query/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/cli-references/monitoring-prometheus/monitoring-prometheus-range/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/cli-references/monitoring-prometheus/monitoring-prometheus-series/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/cli-references/monitoring-prometheus/monitoring-prometheus-status/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/cli-references/monitoring-prometheus/monitoring-prometheus-status/monitoring-prometheus-status-config/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/cli-references/monitoring-prometheus/monitoring-prometheus-status/monitoring-prometheus-status-flags/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/cli-references/monitoring-prometheus/monitoring-prometheus-targets/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/cli-references/monitoring-prometheus/monitoring-prometheus-values/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/configure-dcos-access/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/data.yml
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/data.yml.tmpl
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/getting-started/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/img/alertmanager-dss-gui.png
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/img/alertmanager-slack-alert.png
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/img/grafana-dss-gui.png
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/img/prometheus-dss-gui.png
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/index.md.tmpl
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/operations/alertmanager/config/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/operations/alertmanager/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/operations/alertmanager/slack/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/operations/alertmanager/storage/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/operations/alertmanager/ui/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/operations/grafana/dashboard-configs/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/operations/grafana/default-dashboards/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/operations/grafana/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/operations/grafana/storage/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/operations/grafana/ui/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/operations/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/operations/install/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/operations/placement-constraint/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/operations/prometheus/alert-rules/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/operations/prometheus/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/operations/prometheus/storage/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/operations/prometheus/ui/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/operations/pushgateway/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/operations/uninstall/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/release-notes/index.md
Labels: ready to merge

#2639 Simplify service account provisioning commands using DC/OS CLI
  pages/mesosphere/dcos/services/include/security-create-permissions.tmpl
  pages/mesosphere/dcos/services/include/service-account.tmpl
Labels: ready to merge

#2600 Correct outdated Marathon quota-related information
  pages/mesosphere/dcos/2.0/multi-tenancy/quota-management/index.md
Labels: ready to merge

#2594 Updated Metronome documentation
  pages/mesosphere/dcos/1.12/deploying-jobs/quickstart/index.md
  pages/mesosphere/dcos/1.13/deploying-jobs/quickstart/index.md
  pages/mesosphere/dcos/2.0/deploying-jobs/quickstart/index.md
Labels: ready to merge

#2549 Removes HTTP Path Rewrite within the Edge-LB Pool
  pages/mesosphere/dcos/services/elastic/2.7.0-6.8.1/how-to-guides/index.md
Labels: ready to merge

#2637 co/dcos-61136 (2.0.1 release notes)
  pages/mesosphere/dcos/2.0/release-notes/2.0.1/index.md
Labels: ready to merge

#2634 created draft 1.11.13 release notes
  pages/mesosphere/dcos/1.11/release-notes/1.11.13/index.md
Labels: ready to merge
