Repository mesosphere/dcos-docs-site, pull requests merged in 2019-02, with the labels that each got.

#1902 Fixed typo in autocompletion docs.
  pages/1.12/cli/autocompletion/index.md
Labels: ready to merge

#1887 [DCOS-46527] Add documentation for Elastic and Kibana 2.5.0-6.3.2.
  pages/services/elastic/2.5.0-6.3.2/advanced/index.md
  pages/services/elastic/2.5.0-6.3.2/api-reference/index.md
  pages/services/elastic/2.5.0-6.3.2/configuration/index.md
  pages/services/elastic/2.5.0-6.3.2/getting-started/index.md
  pages/services/elastic/2.5.0-6.3.2/img/private-node-by-vip.png
  pages/services/elastic/2.5.0-6.3.2/img/private-nodes-by-agent.png
  pages/services/elastic/2.5.0-6.3.2/img/x-pack.png
  pages/services/elastic/2.5.0-6.3.2/index.md
  pages/services/elastic/2.5.0-6.3.2/limitations/index.md
  pages/services/elastic/2.5.0-6.3.2/operations/index.md
  pages/services/elastic/2.5.0-6.3.2/release-notes/index.md
  pages/services/elastic/2.5.0-6.3.2/security/index.md
  pages/services/elastic/2.5.0-6.3.2/support-policy/index.md
  pages/services/elastic/2.5.0-6.3.2/troubleshooting/index.md
  pages/services/elastic/2.5.0-6.3.2/uninstall/index.md
  pages/services/elastic/2.5.0-6.3.2/updates/index.md
Labels: ready to merge

#1835 ss/DCOS-41471 Adding AWS session token info to backup operations doc.
  pages/services/cassandra/2.0.1-3.0.14/disaster-recovery/index.md
  pages/services/cassandra/2.0.2-3.0.14/disaster-recovery/index.md
  pages/services/cassandra/2.0.3-3.0.14/disaster-recovery/index.md
  pages/services/cassandra/2.1.0-3.0.16/operations/index.md
  pages/services/cassandra/2.2.0-3.0.16/operations/index.md
  pages/services/cassandra/2.3.0-3.0.16/operations/index.md
  pages/services/cassandra/2.4.0-3.0.16/operations/index.md
Labels: needs writer review

#1826 Add pxc 0.1.0-5.7.21
  pages/services/pxc/0.1.0-5.7.21/Operations/index.md
  pages/services/pxc/0.1.0-5.7.21/cli-reference/index.md
  pages/services/pxc/0.1.0-5.7.21/getting-started/index.md
  pages/services/pxc/0.1.0-5.7.21/img/after_log_in.png
  pages/services/pxc/0.1.0-5.7.21/img/am_dashboard.png
  pages/services/pxc/0.1.0-5.7.21/img/create_user.png
  pages/services/pxc/0.1.0-5.7.21/img/grafana_datasource.png
  pages/services/pxc/0.1.0-5.7.21/img/grafana_login.png
  pages/services/pxc/0.1.0-5.7.21/img/grafana_prom.png
  pages/services/pxc/0.1.0-5.7.21/img/openldap_login.png
  pages/services/pxc/0.1.0-5.7.21/img/prom_dashboard.png
  pages/services/pxc/0.1.0-5.7.21/img/prom_graphing.png
  pages/services/pxc/0.1.0-5.7.21/img/prom_install.png
  pages/services/pxc/0.1.0-5.7.21/index.md
  pages/services/pxc/0.1.0-5.7.21/limitations/index.md
  pages/services/pxc/0.1.0-5.7.21/operations/disaster-recovery/backup/index.md
  pages/services/pxc/0.1.0-5.7.21/operations/disaster-recovery/index.md
  pages/services/pxc/0.1.0-5.7.21/operations/disaster-recovery/restore/index.md
  pages/services/pxc/0.1.0-5.7.21/operations/install/index.md
  pages/services/pxc/0.1.0-5.7.21/operations/security/index.md
  pages/services/pxc/0.1.0-5.7.21/operations/security/service-account/index.md
  pages/services/pxc/0.1.0-5.7.21/operations/troubleshooting/index.md
  pages/services/pxc/0.1.0-5.7.21/operations/troubleshooting/metrics/index.md
  pages/services/pxc/0.1.0-5.7.21/operations/uninstall/index.md
  pages/services/pxc/0.1.0-5.7.21/overview/index.md
  pages/services/pxc/0.1.0-5.7.21/quick-start/index.md
  pages/services/pxc/0.1.0-5.7.21/release-notes/0.1.0-5.7.21/index.md
  pages/services/pxc/0.1.0-5.7.21/release-notes/0.1.1-2.3.2/index.md
  pages/services/pxc/0.1.0-5.7.21/release-notes/index.md
  pages/services/pxc/0.1.0-5.7.21/supported-versions/index.md
  pages/services/pxc/data.yml
  pages/services/pxc/index.md
Labels: DO NOT MERGE

#1994 Added description of Seccomp configuration options.
  pages/1.13/installing/production/advanced-configuration/configuration-reference/index.md
Labels: ready to merge
