Repository mesosphere/dcos-docs-site, pull requests merged in 2019-01, with the labels that each got.

#1813 Add pattern for setting IAM permissions using the API
  pages/1.11/security/ent/perms-management/index.md
  pages/1.12/security/ent/perms-management/index.md
Labels: p2 - normal

#1882 ck/DCOS-45545 Add Windows Instrs to universal installer guides
  pages/1.10/installing/evaluation/aws/index.md
  pages/1.10/installing/evaluation/azure/index.md
  pages/1.10/installing/evaluation/gcp/index.md
  pages/1.11/installing/evaluation/aws/index.md
  pages/1.11/installing/evaluation/azure/index.md
  pages/1.11/installing/evaluation/gcp/index.md
  pages/1.12/installing/evaluation/aws/index.md
  pages/1.12/installing/evaluation/azure/index.md
  pages/1.12/installing/evaluation/gcp/index.md
Labels: needs review

#1889 DCOS-47318 Move AWS region export step to single param config
  pages/1.10/installing/evaluation/aws/index.md
  pages/1.11/installing/evaluation/aws/index.md
  pages/1.12/installing/evaluation/aws/index.md
Labels: needs review

#1876 LG/DCOS-46836 - DRAFT content for 1.10.10 release notes
  pages/1.10/release-notes/1.10.10/index.md
  pages/services/marathon-lb/data.yml
  pages/services/marathon-lb/mlb-install/index.md
Labels: ready to merge
