Repository mesosphere/dcos-docs-site, pull requests merged in 2019-12, with the labels that each got.

#2650 Fixing link to overlay advisory - COPS-4401
  pages/mesosphere/dcos/1.11/installing/production/upgrading/index.md
  pages/mesosphere/dcos/1.12/installing/production/upgrading/index.md
  pages/mesosphere/dcos/1.13/installing/production/upgrading/index.md
  pages/mesosphere/dcos/2.0/installing/production/upgrading/index.md
  pages/mesosphere/dcos/2.1/installing/production/upgrading/index.md
Labels: ready to merge

#2648 Adding missing virt-infra page to DC/OS 1.13 and above (COPS-5416)
  pages/mesosphere/dcos/1.11/installing/production/virt-infra/index.md
  pages/mesosphere/dcos/1.12/installing/production/virt-infra/index.md
  pages/mesosphere/dcos/1.13/installing/production/virt-infra/index.md
  pages/mesosphere/dcos/2.0/installing/production/virt-infra/index.md
  pages/mesosphere/dcos/2.1/installing/production/virt-infra/index.md
Labels: wip

#2656 Correcting note about static IPs in AWS - COPS-4958
  pages/mesosphere/dcos/1.10/installing/production/advanced-configuration/configuration-reference/index.md
  pages/mesosphere/dcos/1.11/installing/production/advanced-configuration/configuration-reference/index.md
  pages/mesosphere/dcos/1.12/installing/production/advanced-configuration/configuration-reference/index.md
  pages/mesosphere/dcos/1.13/installing/production/advanced-configuration/configuration-reference/index.md
  pages/mesosphere/dcos/2.0/installing/production/advanced-configuration/configuration-reference/index.md
  pages/mesosphere/dcos/2.1/installing/production/advanced-configuration/configuration-reference/index.md
Labels: ready to merge

#2658 Add service role examples for enforceRole=true and quota aware versions of packages
  pages/mesosphere/dcos/services/cassandra/2.7.0-3.11.4/security/index.md
  pages/mesosphere/dcos/services/confluent-kafka/2.8.0-5.3.1/security/index.md
  pages/mesosphere/dcos/services/confluent-zookeeper/2.7.0-5.1.2e/security/index.md
  pages/mesosphere/dcos/services/hive-metastore/1.0.0-3.0.0/security/index.md
  pages/mesosphere/dcos/services/include/security-create-permissions.tmpl
  pages/mesosphere/dcos/services/kafka-zookeeper/2.7.0-3.4.14/security/index.md
  pages/mesosphere/dcos/services/kafka/2.8.0-2.3.0/security/index.md
  pages/mesosphere/dcos/services/nifi/1.0.0-1.9.2/security/index.md
Labels: ready to merge

#2663 Adjust menuweights in top level page of each version in NiFi
  pages/mesosphere/dcos/services/nifi/0.1.0-1.5.0/index.md
  pages/mesosphere/dcos/services/nifi/0.2.0-1.5.0/index.md
  pages/mesosphere/dcos/services/nifi/0.3.0-1.7.1/index.md
  pages/mesosphere/dcos/services/nifi/0.4.0-1.8.0/index.md
  pages/mesosphere/dcos/services/nifi/0.4.1-1.8.0/index.md
  pages/mesosphere/dcos/services/nifi/0.5.0-1.9.2/index.md
Labels: ready to merge

#2664 Add image in distributed process management page
  pages/mesosphere/dcos/1.12/overview/architecture/distributed-process-management/index.md
  pages/mesosphere/dcos/1.13/overview/architecture/distributed-process-management/index.md
  pages/mesosphere/dcos/2.0/overview/architecture/distributed-process-management/index.md
  pages/mesosphere/dcos/2.1/overview/architecture/distributed-process-management/index.md
Labels: ready to merge

#2668 Added folder and file for Legal Notices
  pages/mesosphere/dcos/2.0/release-notes/legal-notices/index.md
Labels: ready to merge

#2672 Fix typo (desribe instead of describe)
  pages/mesosphere/dcos/services/dcos-monitoring/1.1.0/cli-references/index.md
Labels: ready to merge

#2670 ss/COPS-4090 Removing secrets suggestion from security/ent/hardening …
  pages/mesosphere/dcos/cn/1.11/security/ent/hardening/index.md
Labels: TRANSLATION, ready to merge

#2673 Fix wrong default URL for Package Registry
  pages/mesosphere/dcos/1.12/administering-clusters/repo/package-registry/quickstart/index.md
Labels: ready to merge

#2674 fix inconsistent secret naming
  pages/mesosphere/dcos/1.13/administering-clusters/package-registry/index.md
  pages/mesosphere/dcos/2.0/administering-clusters/package-registry/index.md
  pages/mesosphere/dcos/2.1/administering-clusters/package-registry/index.md
Labels: ready to merge

#2676 Links correction
  pages/mesosphere/dcos/services/jenkins/3.5.2-2.107.2/quickstart/index.md
  pages/mesosphere/dcos/services/jenkins/3.5.2-2.107.2/upgrade/index.md
  pages/mesosphere/dcos/services/jenkins/3.5.3-2.150.1/quickstart/index.md
  pages/mesosphere/dcos/services/jenkins/3.5.3-2.150.1/upgrade/index.md
  pages/mesosphere/dcos/services/jenkins/3.5.4-2.150.1/quickstart/index.md
  pages/mesosphere/dcos/services/jenkins/3.5.4-2.150.1/upgrade/index.md
Labels: ready to merge

#2669 Ss/dcos 60581
  pages/mesosphere/dcos/1.13/gui/services/index.md
  pages/mesosphere/dcos/2.0/gui/services/index.md
  pages/mesosphere/dcos/2.1/gui/services/index.md
Labels: ready to merge

#2684 Adding release notes for v1.5.1
  pages/mesosphere/dcos/services/edge-lb/1.5/release-notes/index.md
Labels: ready to merge

#2651 Updating systemd units list to match what is in each DC/OS version - COPS-4438
  pages/mesosphere/dcos/1.12/overview/architecture/components/index.md
  pages/mesosphere/dcos/1.13/overview/architecture/components/index.md
  pages/mesosphere/dcos/2.0/overview/architecture/components/index.md
  pages/mesosphere/dcos/2.1/overview/architecture/components/index.md
Labels: ready to merge

#2652 Replacing old zen.sh GPU-enabled cluster build with the DC/OS Universal Installer - COPS-4559
  pages/mesosphere/dcos/1.12/deploying-services/gpu/index.md
  pages/mesosphere/dcos/1.13/deploying-services/gpu/index.md
  pages/mesosphere/dcos/2.0/deploying-services/gpu/index.md
  pages/mesosphere/dcos/2.1/deploying-services/gpu/index.md
Labels: ready to merge

#2657 Removing incorrect note about using quotes with the DC/OS diagnostics CLI - COPS-5280
  pages/mesosphere/dcos/1.10/cli/command-reference/dcos-node/dcos-node-diagnostics-create/index.md
  pages/mesosphere/dcos/1.11/cli/command-reference/dcos-node/dcos-node-diagnostics-create/index.md
  pages/mesosphere/dcos/1.12/cli/command-reference/dcos-node/dcos-node-diagnostics-create/index.md
  pages/mesosphere/dcos/1.13/cli/command-reference/dcos-node/dcos-node-diagnostics-create/index.md
  pages/mesosphere/dcos/2.0/cli/command-reference/dcos-node/dcos-node-diagnostics-create/index.md
  pages/mesosphere/dcos/2.1/cli/command-reference/dcos-node/dcos-node-diagnostics-create/index.md
Labels: wip

#2690 Ru/dcos 61053
  pages/ksphere/kommander/latest/projects/index.md
Labels: wip
