Repository mesosphere/dcos-docs-site, pull requests merged in 2019-10, with the labels that each got.

#2560 ss/DCOS-58757 First draft of release notes, based on change logs for …
  pages/mesosphere/dcos/1.13/release-notes/1.13.5/index.md
Labels: 1.13, ready to merge

#2583 Revert move of How-To guides into the "operations" folder.
  pages/mesosphere/dcos/services/elastic/3.0.0-7.3.2/how-to-guides/index.md
Labels: ready to merge

#2534 [COPS-5317] update the kafka broker configuration explanation
  pages/mesosphere/dcos/services/kafka/2.4.0-1.1.1/started/index.md
  pages/mesosphere/dcos/services/kafka/2.8.0-2.3.0/started/index.md
Labels: ready to merge

#2581 edgelb: post 1.5 release doc updates
  pages/mesosphere/dcos/services/edge-lb/1.5/release-notes/index.md
Labels: ready to merge

#2598 Fixed Upgrade Chart for 2.0
  pages/mesosphere/dcos/2.0/installing/production/upgrading/index.md
Labels: DC/OS 1.14/2.0, ready to merge

#2602 DCOS-60191 Fixing minor typos in Release Notes for 2.0.0.
  pages/mesosphere/dcos/2.0/release-notes/2.0.0/index.md
Labels: DC/OS 1.14/2.0, ready to merge

#2601 [DCOS-60485] Update docs for cassandra 2.7.0-3.11.4
  pages/mesosphere/dcos/services/cassandra/2.7.0-3.11.4/limitations/index.md
Labels: ready to merge

#2604 dcos-monitoring: Update docs for 1.1.0
  pages/mesosphere/dcos/services/dcos-monitoring/1.1.0/configure-dcos-access/index.md
  pages/mesosphere/dcos/services/dcos-monitoring/1.1.0/getting-started/index.md
Labels: ready to merge

#2610 ss/DCOS-60623 Added release date, fixed spelling and formatting.
  pages/mesosphere/dcos/services/edge-lb/1.5/release-notes/index.md
Labels: ready to merge

#2577 Remove information about DC/OS History
  pages/mesosphere/dcos/2.1/api/nginx.master.yaml
  pages/mesosphere/dcos/2.1/installing/production/system-requirements/partitions/index.md
  pages/mesosphere/dcos/2.1/installing/production/system-requirements/ports/index.md
  pages/mesosphere/dcos/2.1/monitoring/logging/aggregating/splunk/index.md
  pages/mesosphere/dcos/2.1/monitoring/logging/quickstart/index.md
  pages/mesosphere/dcos/2.1/overview/architecture/components/index.md
  pages/mesosphere/dcos/2.1/overview/design/azure-container-service/index.md
  pages/mesosphere/dcos/2.1/overview/telemetry/index.md
  pages/mesosphere/dcos/2.1/release-notes/open-source-attribution/index.md
  pages/mesosphere/dcos/2.1/security/ent/gui-permissions/components-tab/index.md
  pages/mesosphere/dcos/2.1/security/ent/perms-reference/index.md
Labels: DC/OS 2.1
