Repository mesosphere/dcos-docs-site, pull requests merged in 2019-04, with the labels that each got.

#2168 Add deprecation infromation for DCOS History
  pages/1.13/api/nginx.master.yaml
  pages/1.13/overview/architecture/components/index.md
  pages/1.13/overview/concepts/index.md
  pages/1.13/overview/design/azure-container-service/index.md
  pages/1.13/release-notes/open-source-attribution/index.md
  pages/1.13/security/ent/perms-reference/index.md
Labels: 1.13, needs writer review

#1908 ck/DCOS-46823 Update to AWS for clarity
  pages/1.10/installing/evaluation/aws/index.md
  pages/1.11/installing/evaluation/aws/index.md
  pages/1.12/installing/evaluation/aws/index.md
Labels: needs eng review

#2167 Fix Admin Router service endpoint permission ref
  pages/1.11/security/ent/perms-reference/index.md
  pages/1.12/security/ent/perms-reference/index.md
  pages/1.13/security/ent/perms-reference/index.md
Labels: needs docs ticket

#2117 Add note about application metrics gather interval
  pages/1.12/metrics/index.md
  pages/1.13/metrics/index.md
Labels: needs docs ticket

#2189 Lg/dcos 47000 seccomp profiles
  pages/1.13/security/ent/secure-compute-profiles/index.md
Labels: needs eng review

#2190 Update certified package versions
  pages/version-policy/index.md
Labels: needs docs ticket
