Repository mesosphere/dcos-docs-site, pull requests merged in 2020-08, with the labels that each got.

#3114 speed up live editing in docker …
  Makefile
  index.js
Labels: doc tools fix, ready to merge

#3125 Update Dispatch docs to staging.
  pages/ksphere/dispatch/1.2/references/api/index.md
  pages/ksphere/dispatch/1.2/tutorials/ci_tutorials/repo-setup/index.md
  pages/ksphere/dispatch/1.3/references/api/index.md
  pages/ksphere/dispatch/1.3/references/pipeline-config-ref/index.md
  pages/ksphere/dispatch/1.3/release-notes/1.3/index.md
  pages/ksphere/dispatch/1.3/tutorials/ci_tutorials/repo-setup/index.md
Labels: Dispatch

#3127 removing dispatch 1.3 from do not build list
  config.json
Labels: Dispatch

#3129 Updated OSS Attributions for Kommander 1.1
  pages/ksphere/kommander/1.1/release-notes/open-source-attributions/index.md
Labels: Kommander, ready to merge

#3130 COPS-6402: Add config parameter which avoids the issue
  pages/mesosphere/dcos/1.13/deploying-services/private-docker-registry/index.md
  pages/mesosphere/dcos/2.0/deploying-services/private-docker-registry/index.md
  pages/mesosphere/dcos/2.1/deploying-services/private-docker-registry/index.md
Labels: DC/OS Improvements, ready to merge

#3134 Update Dispatch docs to staging.
  pages/ksphere/dispatch/1.3/release-notes/1.3/index.md
Labels: Dispatch

#3120 COPS-6362: Fixing incorrect information about Docker credentials in DC/OS
  pages/mesosphere/dcos/1.13/installing/production/advanced-configuration/configuration-reference/index.md
  pages/mesosphere/dcos/2.0/installing/production/advanced-configuration/configuration-reference/index.md
  pages/mesosphere/dcos/2.1/installing/production/advanced-configuration/configuration-reference/index.md
Labels: DC/OS Improvements, ready to merge

#3137 [D2IQ-70666] Change Google Tag Manager container ID.
  layouts/partials/head.pug
Labels: doc tools fix, ready to merge

#3138 fix watching when using RPP on osx
  index.js
Labels: doc tools fix

#3141 chore: adds release date for MKE 2.7.0
  pages/mesosphere/dcos/services/kubernetes/2.7.0-1.18.6/changelog/index.md
  pages/mesosphere/dcos/services/kubernetes/2.7.0-1.18.6/release-notes/index.md
Labels: kubernetes, ready to merge

#3123 remove obsolete entries from config.json
  config.json
  index.js
Labels: doc tools fix, ready to merge

#3136 trim down algolia-plugin
  Makefile
  docker-compose.yml
  docker/Dockerfile.production
  index.js
  js/search.js
  plugins/metalsmith-algolia.js
  scripts/build-site.sh
  webpack.config.js
Labels: doc tools fix, ready to merge

#3145 fix a landingpage link
  layouts/dcos-docs-landing.pug
Labels: DC/OS Improvements, ready to merge

#3143 refactor the headings-plugin and remove some dead code
  layouts/components/content-sections.pug
  plugins/metalsmith-headings.js
Labels: doc tools fix, ready to merge

#3144 refactor hierarchy-plugin and sidebar
  index.js
  layouts/partials/sidebar/en-sidebar.pug
  layouts/partials/sidebar/sidebar.pug
  plugins/metalsmith-hierarchy-rss.js
  plugins/metalsmith-hierarchy.js
Labels: doc tools fix, ready to merge

#3147 fix: improve fault domain example to be a valid script
  pages/mesosphere/dcos/1.13/installing/production/deploying-dcos/installation/index.md
  pages/mesosphere/dcos/2.0/installing/production/deploying-dcos/installation/index.md
  pages/mesosphere/dcos/2.1/installing/production/deploying-dcos/installation/index.md
Labels: DC/OS Improvements, ready to merge

#3150 remove an obsolete layout
  layouts/partials/print-toc.pug
  scss/base/_print-toc.scss
  scss/style.scss
Labels: doc tools fix, ready to merge

#3151 convert templates to use pugs class and id notation
  layouts/404.pug
  layouts/all-products-landing.pug
  layouts/cn-dcos-docs-landing.pug
  layouts/cn-service-docs-landing.pug
  layouts/components/content-actions.pug
  layouts/components/content-grid.pug
  layouts/conductor-docs-landing.pug
  layouts/dcos-docs-landing.pug
  layouts/dispatch-docs-landing.pug
  layouts/kommander-docs-landing.pug
  layouts/konvoy-docs-landing.pug
  layouts/konvoy-partners-landing.pug
  layouts/kudo-kubeflow-docs-landing.pug
  layouts/partials/content.pug
  layouts/partials/header/header-dropdown.pug
  layouts/partials/header/header.pug
  layouts/partials/header/ksphere-dropdown.pug
  layouts/partials/header/localization-dropdown.pug
  layouts/partials/header/mesosphere-dropdown.pug
  layouts/partials/search-results.pug
  layouts/search.pug
  layouts/service-docs-landing.pug
Labels: doc tools fix, ready to merge

#3142 Remove kubecost 3hr wait time from centralized cost monitoring docs
  pages/ksphere/kommander/1.1/centralized-cost-monitoring/index.md
Labels: DO NOT MERGE, Kommander

#3156 Added upgrade paths for 2.05 and 2.06
  pages/mesosphere/dcos/2.0/installing/production/patching/index.md
  pages/mesosphere/dcos/2.0/installing/production/upgrading/index.md
  pages/mesosphere/dcos/2.1/installing/production/upgrading/index.md
Labels: DC/OS, ready to merge

#3158 D2iQ-41078
  layouts/components/content-actions.pug
  scss/components/_actions.scss
Labels: doc tools fix, ready to merge

#3164 Add Proselint
  .github/styles/proselint/Airlinese.yml
  .github/styles/proselint/AnimalLabels.yml
  .github/styles/proselint/Annotations.yml
  .github/styles/proselint/Apologizing.yml
  .github/styles/proselint/Archaisms.yml
  .github/styles/proselint/But.yml
  .github/styles/proselint/Cliches.yml
  .github/styles/proselint/CorporateSpeak.yml
  .github/styles/proselint/Currency.yml
  .github/styles/proselint/Cursing.yml
  .github/styles/proselint/DateCase.yml
  .github/styles/proselint/DateMidnight.yml
  .github/styles/proselint/DateRedundancy.yml
  .github/styles/proselint/DateSpacing.yml
  .github/styles/proselint/DenizenLabels.yml
  .github/styles/proselint/Diacritical.yml
  .github/styles/proselint/GenderBias.yml
  .github/styles/proselint/GroupTerms.yml
  .github/styles/proselint/Hedging.yml
  .github/styles/proselint/Hyperbole.yml
  .github/styles/proselint/Jargon.yml
  .github/styles/proselint/LGBTOffensive.yml
  .github/styles/proselint/LGBTTerms.yml
  .github/styles/proselint/Malapropisms.yml
  .github/styles/proselint/Needless.yml
  .github/styles/proselint/Nonwords.yml
  .github/styles/proselint/Oxymorons.yml
  .github/styles/proselint/P-Value.yml
  .github/styles/proselint/RASSyndrome.yml
  .github/styles/proselint/README.md
  .github/styles/proselint/Skunked.yml
  .github/styles/proselint/Spelling.yml
  .github/styles/proselint/Typography.yml
  .github/styles/proselint/Uncomparables.yml
  .github/styles/proselint/Very.yml
  .github/styles/proselint/meta.json
  .vale.ini
Labels: doc tools fix, ready to merge

#3140 Line Highlighting
  README.md
  js/code-container.js
  package.json
  scss/vendor/_prism.scss
Labels: doc tools fix, ready to merge

#3169 only lint markdown files and ignore shortcodes
  .github/styles/Vocab/Docs/accept.txt
  .github/workflows/vale.yml
  .vale.ini
  pages/index.md
Labels: doc tools fix, ready to merge

#3176 updating PR template so it points to the right things
  pull_request_template
Labels: doc tools fix, ready to merge

#3172 D2IQ-71207 add a border around images in content
  pages/ksphere/konvoy/1.5/concepts/index.md
  scss/base/_content.scss
Labels: doc tools fix, ready to merge

#3178 tweaking vale linter to be more accurate
  .github/styles/Microsoft/Acronyms.yml
  .github/styles/Microsoft/ComplexWords.yml
  .github/styles/Microsoft/HeadingAcronyms.yml
  .github/styles/Vocab/Docs/accept.txt
  .github/styles/Vocab/Docs/reject.txt
Labels: doc tools fix, ready to merge

#3170 feat: document prometheusadapter being federated
  pages/ksphere/kommander/1.2/clusters/attach-cluster/federated-addons/index.md
Labels: Kommander, ready to merge

#3184 correcting versions on deployed 2.1.1 cluster
  pages/mesosphere/dcos/2.1/release-notes/2.1.1/index.md
Labels: DC/OS Improvements, ready to merge

#3187 removing contractions linter
  .github/styles/Microsoft/Contractions.yml
Labels: doc tools fix, ready to merge

#3181 D2IQ-71280: redirects cloud-providers URL to infrastructure-providers
  docker/nginx/redirects-301.map
Labels: Kommander, ready to merge

#3189 allow to set RPP for `npm run build`
  index.js
Labels: doc tools fix, ready to merge
