Repository mesosphere/dcos-docs-site, pull requests merged in 2020-05, with the labels that each got.

#2880 chore: adds Quotas section to Project docs
  pages/ksphere/kommander/1.1.0-beta/img/project-quotas-add-custom.png
  pages/ksphere/kommander/1.1.0-beta/projects/index.md
Labels: Kommander, ready to merge

#2891 COPS-6100: Terraform Universal Installer documentation needs to be updated regarding minimum requirements for main.tf
  pages/mesosphere/dcos/install-include/aws-cluster-setup.tmpl
Labels: DC/OS Improvements, ready to merge

#2893 2.0.3 warning
  pages/mesosphere/dcos/2.0/release-notes/2.0.3/index.md
Labels: DC/OS, wip

#2894 adding link for admin router section
  pages/mesosphere/dcos/2.1/release-notes/2.1.0/index.md
Labels: DC/OS 2.1, ready to merge

#2895 adding product advisory link, fixing typo
  pages/mesosphere/dcos/2.0/release-notes/2.0.3/index.md
Labels: DC/OS, ready to merge

#2905 adding dispatch 1.2 to master do not build
  config.json
Labels: Dispatch

#2912 chore: Update latest kubernetes redirect to 2.5.0-1.16.9
  docker/nginx/redirects-307.map
Labels: ready to merge

#2903 Remove Portworx from Partner Solutions.
  pages/ksphere/konvoy/partner-solutions/portworx/index.md
Labels: KONVOY, ready to merge

#2914 Remove horizontal scrollbar
  scss/base/_global.scss
Labels: doc tools fix

#2896 updating release notes for beta 5
  pages/mesosphere/dcos/2.1/release-notes/2.1.0/index.md
Labels: DC/OS 2.1, ready to merge

#2921 Removing invalid reference link
  pages/mesosphere/dcos/1.12/installing/production/deploying-dcos/opt-out/index.md
  pages/mesosphere/dcos/1.13/installing/production/deploying-dcos/opt-out/index.md
  pages/mesosphere/dcos/2.0/installing/production/deploying-dcos/opt-out/index.md
  pages/mesosphere/dcos/2.1/installing/production/deploying-dcos/opt-out/index.md
Labels: DC/OS Improvements, ready to merge

#2918 Fix build when using dispatch or kommander branch
  config.json
Labels: doc tools fix, ready to merge

#2920 Reapply PR #2853
  pages/ksphere/kommander/1.1.0-beta/clusters/attach-cluster/index.md
Labels: Kommander, ready to merge

#2923 COPS-4103 fixes
  pages/mesosphere/dcos/services/cassandra/2.4.0-3.0.16/configuration/index.md
  pages/mesosphere/dcos/services/cassandra/2.4.0-3.0.16/getting-started/index.md
  pages/mesosphere/dcos/services/cassandra/2.9.0-3.11.6/configuration/index.md
  pages/mesosphere/dcos/services/cassandra/2.9.0-3.11.6/getting-started/index.md
Labels: DC/OS Improvements, ready to merge

#2922 fix robots-txt
  docker/Dockerfile.production
Labels: doc tools fix, ready to merge

#2913 run prettier on js-files and remove linting
  entry.js
  index.js
  js/README.md
  js/actions.js
  js/analytics.js
  js/code-container.js
  js/ellipsis.js
  js/header-dropdown.js
  js/header.js
  js/image.js
  js/ksphere-menu.js
  js/localization.js
  js/main.js
  js/msphere-menu.js
  js/partners-landing.js
  js/search.js
  js/sections.js
  js/services-landing.js
  js/sidebar-drawer.js
  js/sidebar.js
  js/swagger-ui.js
  js/switch.js
  js/tabs.js
  js/toc-scroll.js
  js/tooltip.js
  package.json
  plugins/metalsmith-algolia.js
  plugins/metalsmith-headings.js
  plugins/metalsmith-hierarchy-rss.js
  plugins/metalsmith-hierarchy.js
  plugins/metalsmith-in-place-dcos.js
  plugins/metalsmith-include-content-dcos.js
  plugins/metalsmith-shortcodes.js
  plugins/metalsmith-wkhtmltopdf-link-resolver.js
  postcss.config.js
  webpack.config.js
Labels: doc tools fix, ready to merge

#2917 [kommander] Update centralized monitoring docs
  pages/ksphere/kommander/1.1.0-beta/centralized-monitoring/index.md
Labels: Kommander, ready to merge

#2926 pages: add caching note to dcos-dns and mesos-dns
  pages/mesosphere/dcos/1.13/networking/DNS/index.md
  pages/mesosphere/dcos/1.13/networking/DNS/mesos-dns/index.md
  pages/mesosphere/dcos/2.0/networking/DNS/index.md
  pages/mesosphere/dcos/2.0/networking/DNS/mesos-dns/index.md
  pages/mesosphere/dcos/2.1/networking/DNS/index.md
  pages/mesosphere/dcos/2.1/networking/DNS/mesos-dns/index.md
Labels: DC/OS Improvements

#2930 konvoy: Update docs for konvoy release v1.5.0-beta.3
  pages/ksphere/konvoy/1.5.0-beta/autoscaling/index.md
  pages/ksphere/konvoy/1.5.0-beta/gpu/index.md
  pages/ksphere/konvoy/1.5.0-beta/install/install-airgapped/index.md
  pages/ksphere/konvoy/1.5.0-beta/install/install-aws/index.md
  pages/ksphere/konvoy/1.5.0-beta/install/install-azure/index.md
  pages/ksphere/konvoy/1.5.0-beta/install/install-dev/index.md
  pages/ksphere/konvoy/1.5.0-beta/install/install-onprem/index.md
  pages/ksphere/konvoy/1.5.0-beta/install/install-secured/index.md
  pages/ksphere/konvoy/1.5.0-beta/install/node-pools/index.md
  pages/ksphere/konvoy/1.5.0-beta/networking/index.md
  pages/ksphere/konvoy/1.5.0-beta/operations/managing-nodes/index.md
  pages/ksphere/konvoy/1.5.0-beta/quick-start/index.md
  pages/ksphere/konvoy/1.5.0-beta/reference/addons/index.md
  pages/ksphere/konvoy/1.5.0-beta/reference/cluster-configuration/index.md
  pages/ksphere/konvoy/1.5.0-beta/reference/cluster-configuration/v1beta1/index.md
  pages/ksphere/konvoy/1.5.0-beta/reference/cluster-configuration/v1beta2/index.md
  pages/ksphere/konvoy/1.5.0-beta/reference/command-line-interface/konvoy-check/index.md
  pages/ksphere/konvoy/1.5.0-beta/reference/command-line-interface/konvoy-deploy/index.md
  pages/ksphere/konvoy/1.5.0-beta/reference/command-line-interface/konvoy-deploy/konvoy-deploy-kubernetes/index.md
  pages/ksphere/konvoy/1.5.0-beta/reference/command-line-interface/konvoy-init/index.md
  pages/ksphere/konvoy/1.5.0-beta/reference/command-line-interface/konvoy-provision/index.md
  pages/ksphere/konvoy/1.5.0-beta/reference/command-line-interface/konvoy-up/index.md
  pages/ksphere/konvoy/1.5.0-beta/release-notes/index.md
  pages/ksphere/konvoy/1.5.0-beta/release-notes/kubernetes-base-addon/index.md
  pages/ksphere/konvoy/1.5.0-beta/tutorials/addon-repositories/index.md
  pages/ksphere/konvoy/1.5.0-beta/tutorials/provision-a-custom-cluster/index.md
  pages/ksphere/konvoy/1.5.0-beta/upgrade/upgrade-kubernetes-addons/index.md
Labels: KONVOY, ready to merge

#2929 Update Dispatch docs to staging.
  pages/ksphere/dispatch/1.0/pipeline-configuration/index.md
  pages/ksphere/dispatch/1.1/operations/logging/index.md
  pages/ksphere/dispatch/1.1/pipeline-configuration/index.md
  pages/ksphere/dispatch/1.1/release-notes/1.1.1/index.md
  pages/ksphere/dispatch/1.1/release-notes/1.1/index.md
  pages/ksphere/dispatch/1.1/release-notes/index.md
  pages/ksphere/dispatch/1.2/credentials/index.md
  pages/ksphere/dispatch/1.2/install/index.md
  pages/ksphere/dispatch/1.2/operations/logging/index.md
  pages/ksphere/dispatch/1.2/pipeline-configuration/index.md
Labels: Dispatch, ready to merge

#2928 Release Notes for Kommander 1.0.1 patch.
  pages/ksphere/kommander/1.0/release-notes/index.md
Labels: Kommander, ready to merge

#2935 don't ban crawlers from production
  docker/Dockerfile.production
Labels: doc tools fix, ready to merge

#2933 konvoy: Update docs for konvoy release v1.5.0-beta.4
  pages/ksphere/konvoy/1.5.0-beta/release-notes/index.md
Labels: KONVOY, ready to merge

#2936 Increase instance sizes for DC/OS multi-region install instructions
  pages/mesosphere/dcos/install-include/aws-remote-region-all.tmpl
Labels: DC/OS Improvements, ready to merge

#2939 konvoy: Update docs for konvoy release v1.5.0-beta.5
  pages/ksphere/konvoy/1.5.0-beta/install/supported-operating-systems/index.md
Labels: KONVOY, ready to merge

#2940 Updated DC/OS Metrics Quickstart Formatting: DCOS_OSS-5294
  pages/mesosphere/dcos/1.13/metrics/quickstart/index.md
  pages/mesosphere/dcos/2.0/metrics/quickstart/index.md
  pages/mesosphere/dcos/2.1/metrics/quickstart/index.md
Labels: DC/OS Improvements, ready to merge

#2946 Fixed Mesos version in 2.0.3 release notes.
  pages/mesosphere/dcos/2.0/release-notes/2.0.3/index.md
Labels: DC/OS, ready to merge

#2941 [DC/OS D2IQ-38763]: remove Parameters key from Docker object in Marathon service section
  pages/mesosphere/dcos/1.11/deploying-services/creating-services/deploy-docker-app/index.md
  pages/mesosphere/dcos/1.12/deploying-services/creating-services/deploy-docker-app/index.md
  pages/mesosphere/dcos/1.13/deploying-services/creating-services/deploy-docker-app/index.md
  pages/mesosphere/dcos/2.0/deploying-services/creating-services/deploy-docker-app/index.md
  pages/mesosphere/dcos/2.1/deploying-services/creating-services/deploy-docker-app/index.md
Labels: DC/OS Improvements, ready to merge

#2947 Fixed Mesos and OpenSSL versions in 2.0.4 release notes.
  pages/mesosphere/dcos/2.0/release-notes/2.0.4/index.md
Labels: DC/OS, ready to merge

#2944 Typo: Adding missing permissions on EdgeLB
  pages/mesosphere/dcos/services/edge-lb/1.5/getting-started/installing/index.md
Labels: DC/OS Improvements, DC/OS Services, ready to merge

#2950 fixing backup information to point to correct topic
  pages/mesosphere/dcos/1.13/administering-clusters/replacing-a-master-node/index.md
  pages/mesosphere/dcos/2.0/administering-clusters/replacing-a-master-node/index.md
  pages/mesosphere/dcos/2.1/administering-clusters/replacing-a-master-node/index.md
Labels: DC/OS Improvements, ready to merge

#2949 Modify Exhibitor access to support TLS where appropriate
  pages/mesosphere/dcos/1.13/installing/troubleshooting/index.md
  pages/mesosphere/dcos/2.0/installing/production/patching/index.md
  pages/mesosphere/dcos/2.0/installing/production/system-requirements/ports/index.md
  pages/mesosphere/dcos/2.0/installing/production/upgrading/index.md
  pages/mesosphere/dcos/2.0/installing/troubleshooting/index.md
  pages/mesosphere/dcos/2.0/security/ent/tls-ssl/exhibitor/index.md
  pages/mesosphere/dcos/2.1/installing/production/patching/index.md
  pages/mesosphere/dcos/2.1/installing/production/system-requirements/ports/index.md
  pages/mesosphere/dcos/2.1/installing/production/upgrading/index.md
  pages/mesosphere/dcos/2.1/installing/troubleshooting/index.md
  pages/mesosphere/dcos/2.1/security/ent/tls-ssl/exhibitor/index.md
Labels: DC/OS Improvements, ready to merge

#2948 DCOS_OSS-5298 custom metrics
  pages/mesosphere/dcos/1.13/metrics/index.md
  pages/mesosphere/dcos/2.0/metrics/index.md
  pages/mesosphere/dcos/2.1/metrics/index.md
Labels: DC/OS Improvements, ready to merge

#2951 Add EKS cluster topic
  pages/ksphere/kommander/1.1.0-beta/clusters/attach-eks-cluster/index.md
Labels: Kommander, ready to merge

#2953 Remove steps related to manual provisioning of root certificate for attached clusters
  pages/ksphere/kommander/1.1.0-beta/clusters/attach-cluster/index.md
Labels: Kommander, needs docs dev review, ready to merge

#2952 Changed HAProxy to link to custom CA and external certificates
  pages/mesosphere/dcos/1.10/security/ent/tls-ssl/haproxy-adminrouter/index.md
  pages/mesosphere/dcos/1.11/security/ent/tls-ssl/haproxy-adminrouter/index.md
  pages/mesosphere/dcos/1.12/security/ent/tls-ssl/haproxy-adminrouter/index.md
  pages/mesosphere/dcos/1.13/security/ent/tls-ssl/haproxy-adminrouter/index.md
  pages/mesosphere/dcos/2.0/security/ent/tls-ssl/haproxy-adminrouter/index.md
  pages/mesosphere/dcos/2.1/security/ent/tls-ssl/haproxy-adminrouter/index.md
Labels: DC/OS Improvements, ready to merge

#2943 Adding instructions for exposing Monitoring over EdgeLB
  pages/mesosphere/dcos/services/dcos-monitoring/1.3.0/configuring-edge-lb/index.md
Labels: DC/OS Services, ready to merge

#2954 adding statement to exhibitor_explicit_keys
  pages/mesosphere/dcos/1.13/installing/production/advanced-configuration/configuration-reference/index.md
  pages/mesosphere/dcos/2.0/installing/production/advanced-configuration/configuration-reference/index.md
  pages/mesosphere/dcos/2.1/installing/production/advanced-configuration/configuration-reference/index.md
Labels: DC/OS Improvements, ready to merge
