Repository mesosphere/dcos-docs-site, pull requests merged in 2020-10, with the labels that each got.

#3248 Update index.md
  pages/ksphere/kubeflow/1.0.1-0.5.0/install/konvoy/index.md
Labels: kubeflow, ready to merge

#3253 pages/ksphere/kommander/1.2/tutorials/project-administrator/index.md …
  pages/ksphere/kommander/1.2/tutorials/project-administrator/index.md
Labels: Kommander, ready to merge

#3263 Fixing Mesos-DNS documentation to avoid customer confusion.
  pages/mesosphere/dcos/1.12/networking/DNS/mesos-dns/index.md
  pages/mesosphere/dcos/1.13/networking/DNS/mesos-dns/index.md
  pages/mesosphere/dcos/2.0/networking/DNS/mesos-dns/index.md
  pages/mesosphere/dcos/2.1/networking/DNS/mesos-dns/index.md
  pages/mesosphere/dcos/2.2/networking/DNS/mesos-dns/index.md
Labels: DC/OS Improvements, ready to merge

#3265 D2IQ-72131: remove references to Secret and ConfigMap display name fields
  pages/ksphere/kommander/1.2/img/project-create-configmap.png
  pages/ksphere/kommander/1.2/img/project-create-secret.png
  pages/ksphere/kommander/1.2/projects/project-configmaps/index.md
  pages/ksphere/kommander/1.2/projects/project-secrets/index.md
Labels: Kommander, ready to merge

#3266 D2IQ-72129: updates IDP docs with SAML provider option
  pages/ksphere/kommander/1.2/img/Identity-provider-Github.png
  pages/ksphere/kommander/1.2/img/Identity-provider-LDAP.png
  pages/ksphere/kommander/1.2/img/Identity-provider-OIDC.png
  pages/ksphere/kommander/1.2/img/Identity-provider-SAML.png
  pages/ksphere/kommander/1.2/operations/identity-providers/index.md
Labels: Kommander, ready to merge

#3262 D2IQ-72130: resource alert settings
  pages/ksphere/kommander/1.2/backup-and-restore/index.md
  pages/ksphere/kommander/1.2/img/resource-warning-settings-chart-example.png
  pages/ksphere/kommander/1.2/img/resource-warning-settings.png
  pages/ksphere/kommander/1.2/resource-alert-settings/index.md
  pages/ksphere/kommander/1.2/troubleshooting/index.md
  pages/ksphere/kommander/1.2/tutorials/index.md
  pages/ksphere/kommander/1.2/uninstall/index.md
Labels: Kommander, ready to merge

#3267 D2IQ-72132: adds info about upgrading project addons
  pages/ksphere/kommander/1.2/img/project-catalog-addon-edit.png
  pages/ksphere/kommander/1.2/projects/platform-services/index.md
Labels: Kommander, ready to merge

#3202 Update OS policy
  pages/mesosphere/dcos/version-policy/index.md
Labels: DC/OS Improvements, ready to merge

#3270 D2IQ-72119: Document infra provider view
  pages/ksphere/kommander/1.2/release-notes/index.md
Labels: Kommander, ready to merge

#3271 chore: update verbiage cloud provider -> infrastructure provider
  pages/ksphere/kommander/1.2/tutorials/duplicating-cluster/index.md
Labels: doc-athon, ready to merge

#3280 Updated ConfigMap
  pages/ksphere/kommander/1.2/projects/project-configmaps/index.md
Labels: doc-athon, ready to merge

#3284 quick PR to fix beta docs and non md links
  pages/ksphere/kommander/1.2/operations/access-control/index.md
Labels: doc-athon, ready to merge

#3281 Small Update
  pages/ksphere/kommander/1.2/projects/platform-services/index.md
Labels: doc-athon, ready to merge

#3273 Kommander project admin tutorial
  pages/ksphere/kommander/1.2/tutorials/project-administrator/index.md
Labels: doc-athon, ready to merge

#3275 Point to corresponding Konvoy uninstall docs instead of latest
  pages/ksphere/kommander/1.2/uninstall/index.md
Labels: doc-athon, ready to merge

#3276 Added Federation Definition
  pages/ksphere/kommander/1.2/projects/index.md
Labels: doc-athon

#3278 Update troubleshooting link to point to latest
  pages/ksphere/kommander/1.2/troubleshooting/index.md
Labels: doc-athon, ready to merge

#3285 QA fixing layout for pages/ksphere/kommander/1.2/clusters/attach-clus…
  pages/ksphere/kommander/1.2/clusters/attach-cluster/attach-eks-cluster/index.md
Labels: ready to merge

#3286 Add etcd and calico ports
  pages/mesosphere/dcos/2.1/installing/production/system-requirements/ports/index.md
  pages/mesosphere/dcos/2.2/installing/production/system-requirements/ports/index.md
Labels: DC/OS 2.1, DC/OS 2.2, DC/OS Improvements, ready to merge

#3287 COPS-6601: "Zones and Regions" page missing Enterprise tag
  pages/mesosphere/dcos/1.13/installing/production/advanced-configuration/configuring-zones-regions/index.md
  pages/mesosphere/dcos/2.0/installing/production/advanced-configuration/configuring-zones-regions/index.md
  pages/mesosphere/dcos/2.1/installing/production/advanced-configuration/configuring-zones-regions/index.md
  pages/mesosphere/dcos/2.2/installing/production/advanced-configuration/configuring-zones-regions/index.md
Labels: ready to merge

#3288 adding note about metrics-server to pages/ksphere/kommander/1.2/clust…
  pages/ksphere/kommander/1.2/clusters/attach-cluster/attach-eks-cluster/index.md
Labels: Kommander, ready to merge

#3290 fix: show centralized monitoring tab in kommander 1.2 docs
  pages/ksphere/kommander/1.2/centralized-monitoring/index.md
Labels: Kommander, ready to merge

#3291 Improve instructions for Exhibitor TLS on upgrade
  pages/mesosphere/dcos/2.0/administering-clusters/replacing-a-master-node/index.md
  pages/mesosphere/dcos/2.0/installing/production/upgrading/index.md
  pages/mesosphere/dcos/2.0/security/ent/tls-ssl/exhibitor/index.md
  pages/mesosphere/dcos/2.1/administering-clusters/replacing-a-master-node/index.md
  pages/mesosphere/dcos/2.1/installing/production/upgrading/index.md
  pages/mesosphere/dcos/2.1/security/ent/tls-ssl/exhibitor/index.md
  pages/mesosphere/dcos/2.2/administering-clusters/replacing-a-master-node/index.md
  pages/mesosphere/dcos/2.2/installing/production/upgrading/index.md
  pages/mesosphere/dcos/2.2/security/ent/tls-ssl/exhibitor/index.md
Labels: DC/OS Improvements, ready to merge

#3277 Update Project Namespace Definition
  pages/ksphere/kommander/1.2/projects/index.md
Labels: doc-athon, ready to merge

#3296 Removing reference to CoreOS
  pages/mesosphere/dcos/1.13/deploying-services/faq/index.md
  pages/mesosphere/dcos/2.0/deploying-services/faq/index.md
  pages/mesosphere/dcos/2.1/deploying-services/faq/index.md
  pages/mesosphere/dcos/2.2/deploying-services/faq/index.md
Labels: DC/OS Improvements, ready to merge

#3298 backporting changes for helm repo location
  pages/ksphere/konvoy/1.4/reference/addons/index.md
  pages/ksphere/konvoy/1.5/reference/addons/index.md
Labels: Kommander, ready to merge

#3279 Example Project Object
  pages/ksphere/kommander/1.2/projects/index.md
Labels: Kommander, doc-athon, ready to merge

#3299 lint only changed lines
  .github/workflows/vale.yml
Labels: doc tools fix, ready to merge

#3308 Removed references to possible GPL usages
  pages/ksphere/dispatch/1.3/release-notes/open-source-attribution/index.md
Labels: Dispatch, ready to merge

#3307 fixing order of TOC drop down
  index.js
  pages/mesosphere/dcos/1.11/index.md
  pages/mesosphere/dcos/1.13/index.md
  pages/mesosphere/dcos/2.0/index.md
  pages/mesosphere/dcos/2.1/index.md
Labels: DC/OS 2.2, GA

#3309 Add guide on how to remove clusters stuck in pending state.
  pages/ksphere/kommander/1.1/troubleshooting/index.md
  pages/ksphere/kommander/1.2/troubleshooting/index.md
Labels: Kommander, ready to merge

#3311 Improve Kommander Tutorial - Use Variables for Namespaces
  pages/ksphere/kommander/1.2/tutorials/use-kcl-from-kubectl/index.md
Labels: Kommander, ready to merge

#3314 Update s3config.json
  s3config.json
Labels: DC/OS 2.2, ready to merge
