Repository mesosphere/dcos-docs-site, pull requests merged in 2020-01, with the labels that each got.

#2671 ss/DCOS-53751 Removing unsupported claim of zone awareness in hybrid…
  pages/mesosphere/dcos/1.13/deploying-services/fault-domain-awareness/index.md
  pages/mesosphere/dcos/1.13/hybrid-cloud/capacity-extension-with-regions/index.md
  pages/mesosphere/dcos/2.0/deploying-services/fault-domain-awareness/index.md
  pages/mesosphere/dcos/2.0/hybrid-cloud/capacity-extension-with-regions/index.md
  pages/mesosphere/dcos/2.1/deploying-services/fault-domain-awareness/index.md
  pages/mesosphere/dcos/2.1/hybrid-cloud/capacity-extension-with-regions/index.md
Labels: ready to merge

#2679 [DCOS-61614] Add release docs for Cassandra 2.8.0-3.11.5
  docker/nginx/redirects-307.map
  pages/mesosphere/dcos/services/cassandra/2.8.0-3.11.5/advanced/index.md
  pages/mesosphere/dcos/services/cassandra/2.8.0-3.11.5/api-reference/index.md
  pages/mesosphere/dcos/services/cassandra/2.8.0-3.11.5/configuration/index.md
  pages/mesosphere/dcos/services/cassandra/2.8.0-3.11.5/getting-started/index.md
  pages/mesosphere/dcos/services/cassandra/2.8.0-3.11.5/index.md
  pages/mesosphere/dcos/services/cassandra/2.8.0-3.11.5/limitations/index.md
  pages/mesosphere/dcos/services/cassandra/2.8.0-3.11.5/operations/index.md
  pages/mesosphere/dcos/services/cassandra/2.8.0-3.11.5/release-notes/index.md
  pages/mesosphere/dcos/services/cassandra/2.8.0-3.11.5/security/index.md
  pages/mesosphere/dcos/services/cassandra/2.8.0-3.11.5/support-policy/index.md
  pages/mesosphere/dcos/services/cassandra/2.8.0-3.11.5/troubleshooting/index.md
  pages/mesosphere/dcos/services/cassandra/2.8.0-3.11.5/uninstall/index.md
  pages/mesosphere/dcos/services/cassandra/2.8.0-3.11.5/updates/index.md
  pages/mesosphere/dcos/version-policy/index.md
Labels: ready to merge

#2697 ss/DCOS-62552 Fixes for DC/OS 2.0.1 Release Notes
  pages/mesosphere/dcos/2.0/release-notes/2.0.1/index.md
Labels: ready to merge

#2706 redirecting services/kubernetes to version 2.4.6-1.15.6
  docker/nginx/redirects-307.map
Labels: wip

#2710 Add docs on centralized monitoring for Kommander
  pages/ksphere/kommander/latest/centralized-monitoring/index.md
Labels: Kommander

#2712 [DCOS-61928] feat: add more clarity to backup/restore
  pages/ksphere/kommander/latest/backup-and-restore/index.md
Labels: wip

#2717 Add warning about unsupported Istio f/Konvoy
  pages/ksphere/konvoy/latest/tutorials/use-istio/index.md
Labels: wip

#2727 ss/DCOS-62713 Edits to new Jenkins on Konvoy doc.
  pages/ksphere/konvoy/partner-solutions/jenkins/index.md
Labels: ready to merge

#2725 [kommander] Docs on federated alert rules
  pages/ksphere/kommander/latest/centralized-monitoring/index.md
Labels: Kommander, ready to merge

#2728 Add category "Workload" to Jenkins page
  pages/ksphere/konvoy/partner-solutions/jenkins/index.md
Labels: ready to merge

#2734 Bug fix added to the Prometheus doc
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/Operations/index.md
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/configuration/alerting-overview/index.md
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/configuration/index.md
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/configuration/prometheus-federation/index.md
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/configuration/remote-storage/index.md
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/configuration/service-discovery/index.md
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/configuration/visualization/index.md
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/getting-started/index.md
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/img/am_dashboard.png
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/img/grafana_datasource.png
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/img/grafana_login.png
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/img/grafana_prom.png
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/img/prom_dashboard.png
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/img/prom_graphing.png
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/img/prom_install.png
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/img/pushg.png
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/img/slack_alert.png
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/index.md
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/limitations/index.md
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/release-notes/index.md
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/security/index.md
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/supported-versions/index.md
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/troubleshooting/index.md
  pages/mesosphere/dcos/services/prometheus/0.1.2-2.3.2/uninstall/index.md
Labels: ready to merge

#2720 draft dcos 2.0.2 release notes
  pages/mesosphere/dcos/2.0/release-notes/2.0.2/index.md
Labels: ready to merge
