Repository mesosphere/dcos-docs-site, pull requests merged in 2020-02, with the labels that each got.

#2747 Ru/d2 iq 63420
  pages/ksphere/konvoy/latest/release-notes/open-source-attribution/index.md
Labels: blocked, ready to merge

#2754 [COPS-5739] - add a bugfix to the release notes of 1.13.6
  pages/mesosphere/dcos/1.13/release-notes/1.13.6/index.md
Labels: ready to merge

#2755 updated ansible docs: use ansible-galaxy instead of mazer
  pages/mesosphere/dcos/1.12/installing/production/dcos-ansible/ansible-quickstart/index.md
  pages/mesosphere/dcos/1.13/installing/production/dcos-ansible/ansible-quickstart/index.md
  pages/mesosphere/dcos/2.0/installing/production/dcos-ansible/ansible-quickstart/index.md
Labels: ready to merge

#2758 fixing release notes for 2.1 release
  pages/mesosphere/dcos/2.1/release-notes/2.1.0/index.md
Labels: ready to merge

#2738 Add documentation for `mesos_http_executor_domain_sockets`
  pages/mesosphere/dcos/2.1/installing/production/advanced-configuration/configuration-reference/index.md
Labels: DC/OS 2.1, wip

#2760 Replace missing legal notice topic and directory.
  pages/ksphere/kommander/latest/release-notes/legal-notices/index.md
Labels: ready to merge

#2753 [D2IQ-62515] HiveMS 1.1.0-3.0.0 specific update on release notes section
  pages/mesosphere/dcos/services/hive-metastore/1.1.0-3.0.0/release-notes/index.md
Labels: ready to merge

#2762 Fix figure number and nav bar issues
  pages/ksphere/kommander/latest/operations/access-control/index.md
  pages/ksphere/kommander/latest/operations/cloud-providers/index.md
Labels: Kommander, ready to merge

#2766 [D2IQ-64347]Update package-registry docs
  pages/mesosphere/dcos/1.13/administering-clusters/package-registry/index.md
  pages/mesosphere/dcos/2.0/administering-clusters/package-registry/index.md
  pages/mesosphere/dcos/2.1/administering-clusters/package-registry/index.md
Labels: needs docs dev review, wip

#2767 D2IQ-64369: Add AWS role based cloud provider
  pages/ksphere/kommander/latest/operations/cloud-providers/index.md
Labels: Kommander, ready to merge

#2769 add license portal info
  pages/ksphere/kommander/latest/licensing/index.md
Labels: Kommander, ready to merge

#2771 SSO for Kubernetes API of attached non-Konvoy clusters
  pages/ksphere/kommander/latest/clusters/attach-cluster/index.md
Labels: Kommander, ready to merge

#2774 feat(Licensing): how to get a kommander license
  pages/ksphere/kommander/latest/licensing/index.md
Labels: Kommander, wip

#2785 Add links from Introduction to Kommander to relevant sections
  pages/ksphere/kommander/latest/introducing-kommander/index.md
Labels: Kommander, ready to merge

#2778 docs(kommander): fix cloud providers image
  pages/ksphere/kommander/latest/operations/cloud-providers/index.md
Labels: Kommander, ready to merge

#2792 Remove top level beta tags for Kommander and Dispatch
  layouts/all-products-landing.pug
Labels: Dispatch, Kommander, ready to merge
