Repository mesosphere/dcos-docs-site, pull requests merged in 2020-11, with the labels that each got.

#3317 accessing archived docs
  pages/mesosphere/dcos/2.2/archives/index.md
Labels: DC/OS 2.2, ready to merge

#3318 fix: document konvoy-addons-chart-repo tag adjustment need
  pages/ksphere/kommander/1.2/install-airgapped/index.md
Labels: Kommander

#3322 remove a troublesome line break
  layouts/partials/head.pug
Labels: doc tools fix, ready to merge

#3321 Fix wrong upgrade guide link
  pages/mesosphere/dcos/install-include-0.3/aws-intro-and-prereqs.tmpl
Labels: DC/OS Improvements, ready to merge

#3327 Update 2.2 oss licenses
  pages/mesosphere/dcos/2.2/release-notes/open-source-attribution/index.md
Labels: DC/OS 2.2, ready to merge

#3329 [DOC] Copied Konvoy topics over for Docker Hub Rate limit.
  pages/ksphere/konvoy/1.6/release-notes/index.md
Labels: Konvoy

#3333 fixing image for Kaptain
  layouts/all-products-landing.pug
Labels: Kaptain, ready to merge

#3332 updating repos for helm charts to be on upstream repos
  pages/ksphere/kommander/1.0/centralized-monitoring/index.md
  pages/ksphere/kommander/1.1/centralized-monitoring/index.md
  pages/ksphere/kommander/1.1/projects/platform-services/index.md
  pages/ksphere/kommander/1.2/centralized-monitoring/index.md
  pages/ksphere/kommander/1.2/projects/platform-services/index.md
Labels: Kommander, ready to merge

#3336 Add documentation for calico_enabled flag
  pages/mesosphere/dcos/2.1/installing/production/advanced-configuration/configuration-reference/index.md
  pages/mesosphere/dcos/2.2/installing/production/advanced-configuration/configuration-reference/index.md
Labels: DC/OS Improvements, ready to merge

#3335 backport helm repo location changes to previous versions of docs
  pages/ksphere/konvoy/1.4/monitoring/index.md
  pages/ksphere/konvoy/1.4/networking/index.md
  pages/ksphere/konvoy/1.4/reference/addons/index.md
  pages/ksphere/konvoy/1.4/release-notes/index.md
  pages/ksphere/konvoy/1.4/tutorials/addon-repositories/index.md
  pages/ksphere/konvoy/1.4/tutorials/use-istio/index.md
  pages/ksphere/konvoy/1.5/monitoring/index.md
  pages/ksphere/konvoy/1.5/networking/index.md
  pages/ksphere/konvoy/1.5/reference/addons/index.md
  pages/ksphere/konvoy/1.5/release-notes/index.md
  pages/ksphere/konvoy/1.5/tutorials/addon-repositories/index.md
Labels: Konvoy, backport, ready to merge

#3337 Remove section for unsupported operation of changing service account creds
  pages/mesosphere/dcos/1.13/security/oss/user-account-management/service-accounts/index.md
  pages/mesosphere/dcos/2.0/security/oss/user-account-management/service-accounts/index.md
  pages/mesosphere/dcos/2.1/security/oss/user-account-management/service-accounts/index.md
  pages/mesosphere/dcos/2.2/security/oss/user-account-management/service-accounts/index.md
Labels: DC/OS Improvements, ready to merge

#3341 fixing link in release notes
  pages/ksphere/kommander/1.2/release-notes/index.md
Labels: Kommander, ready to merge

#3345 Add DC/OS 2.1.2 release notes
  pages/mesosphere/dcos/2.1/release-notes/2.1.2/index.md
Labels: DC/OS 2.1

#3346 Added Konvoy 1.6 OSS attributions
  pages/dkp/konvoy/1.6/legal/open-source-attribution/index.md
Labels: Konvoy, backport, ready to merge

#3344 remove obsolete scripts
  Makefile
  docker-compose.yml
  scripts/build-site.sh
  scripts/count-words.sh
  scripts/links/lib/filename_list.rb
  scripts/links/lib/link.rb
  scripts/links/lib/link_finder.rb
  scripts/links/lib/link_fixer.rb
  scripts/links/lib/redirect.rb
  scripts/links/lib/redirect_map.rb
  scripts/links/lib/redirect_regex.rb
  scripts/links/lib/redirect_string.rb
  scripts/links/redirects_replace_old.rb
  scripts/links/redirects_replace_old.sh
  scripts/service_count_words.rb
Labels: doc tools fix, ready to merge

#3349 fixing spelling of air gapped
  pages/dkp/dispatch/1.0/operations/airgap-support/index.md
  pages/dkp/dispatch/1.0/operations/index.md
  pages/dkp/dispatch/1.1/operations/airgap-support/index.md
  pages/dkp/dispatch/1.1/operations/index.md
  pages/dkp/dispatch/1.2/operations/airgap-support/index.md
  pages/dkp/dispatch/1.2/operations/index.md
  pages/dkp/dispatch/1.3/operations/airgap-support/index.md
  pages/dkp/dispatch/1.3/operations/index.md
  pages/dkp/kaptain/1.0.1-0.5.0/install/air-gapped/index.md
  pages/dkp/kaptain/1.0.1-0.5.0/install/index.md
  pages/dkp/kaptain/1.0.1-0.5.0/tutorials/pipelines/index.md
  pages/dkp/kaptain/1.0.1-0.5.0/tutorials/training/spark/index.md
  pages/dkp/kommander/1.2/install-airgapped/index.md
  pages/dkp/konvoy/1.4/install/install-airgapped/index.md
  pages/dkp/konvoy/1.4/install/install-secured/index.md
  pages/dkp/konvoy/1.4/reference/cluster-configuration/index.md
  pages/dkp/konvoy/1.4/release-notes/index.md
  pages/dkp/konvoy/1.5/autoscaling/index.md
  pages/dkp/konvoy/1.5/gpu/index.md
  pages/dkp/konvoy/1.5/install/install-airgapped/index.md
  pages/dkp/konvoy/1.5/reference/cluster-configuration/v1beta1/index.md
  pages/dkp/konvoy/1.5/reference/cluster-configuration/v1beta2/index.md
  pages/dkp/konvoy/1.5/release-notes/index.md
  pages/dkp/konvoy/1.6/autoscaling/index.md
  pages/dkp/konvoy/1.6/gpu/index.md
  pages/dkp/konvoy/1.6/install/install-airgapped/index.md
  pages/dkp/konvoy/1.6/reference/cluster-configuration/v1beta1/index.md
  pages/dkp/konvoy/1.6/reference/cluster-configuration/v1beta2/index.md
  pages/dkp/konvoy/1.6/release-notes/index.md
  pages/mesosphere/dcos/1.13/administering-clusters/deploying-a-local-dcos-universe/index.md
  pages/mesosphere/dcos/1.13/administering-clusters/package-registry/index.md
  pages/mesosphere/dcos/1.13/gui/updating-gui/index.md
  pages/mesosphere/dcos/2.0/administering-clusters/package-registry/index.md
  pages/mesosphere/dcos/2.0/gui/updating-gui/index.md
  pages/mesosphere/dcos/2.1/administering-clusters/package-registry/index.md
  pages/mesosphere/dcos/2.1/gui/updating-gui/index.md
  pages/mesosphere/dcos/2.2/administering-clusters/package-registry/index.md
  pages/mesosphere/dcos/2.2/gui/updating-gui/index.md
  pages/mesosphere/dcos/services/beta-jenkins/4.0.0-2.204.2-beta/custom-install/index.md
  pages/mesosphere/dcos/services/edge-lb/1.5/getting-started/installing/index.md
  pages/mesosphere/dcos/services/jenkins/4.0.0-2.204.6/custom-install/index.md
Labels: DC/OS Improvements, Dispatch, Kommander, Konvoy

#3351 chore: update latest redirects for konvoy+kommander
  s3config.json
Labels: Kommander, Konvoy

#3356 updated the OSS licesnes for Kommander 1.2
  pages/dkp/kommander/1.2/release-notes/open-source-attributions/index.md
Labels: Kommander, ready to merge

#3355 adding 1.3.1 release notes
  pages/dkp/dispatch/1.3/release-notes/1.3.1/index.md
Labels: Dispatch, ready to merge

#3358 less redirecting
  layouts/partials/sidebar.pug
Labels: doc tools fix

#3360 remove addThis
  js/actions.js
  js/main.js
  layouts/components/content-actions.pug
  layouts/partials/scripts.pug
Labels: doc tools fix
